**EDA**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
base_path = "/content/drive/MyDrive/AI-Powered Hospitality Revenue Optimization/Dataset/"

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv(base_path + "hotel_bookings.csv")

In [ ]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01-07-15
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01-07-15
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02-07-15
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02-07-15
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03-07-15

In [ ]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06-09-17
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07-09-17
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07-09-17
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07-09-17
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07-09-17

In [ ]:
df.shape

(119390, 32)

In [ ]:
print(df.columns.tolist())

['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date']

In [ ]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [ ]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [ ]:
df.describe(include="object")

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
count,119390,119390,119390,118902,119390,119390,119390,119390,119390,119390,119390,119390
unique,2,12,5,177,8,5,10,12,3,4,3,926
top,City Hotel,August,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,21-10-15
freq,79330,13877,92310,48590,56477,97870,85994,74053,104641,89613,75166,1461

In [ ]:
df["hotel"].value_counts()

hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

In [ ]:
df["hotel"].value_counts(normalize=True) * 100

hotel
City Hotel      66.446101
Resort Hotel    33.553899
Name: proportion, dtype: float64

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(31994)

In [ ]:
categorical_columns = [
    "hotel",
    "meal",
    "market_segment",
    "distribution_channel",
    "reserved_room_type",
    "assigned_room_type",
    "deposit_type",
    "customer_type",
    "reservation_status"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- hotel ---
hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

--- meal ---
meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

--- market_segment ---
market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

--- distribution_channel ---
distribution_channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64

--- reserved_room_type ---
reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

--- assigned_room_type ---
assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

--- deposit_type ---
deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64

--- customer_type ---
customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

--- reservation_status ---
reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64

In [ ]:
print("Minimum ADR:", df["adr"].min())
print("Maximum ADR:", df["adr"].max())

print("Minimum lead time:", df["lead_time"].min())
print("Maximum lead time:", df["lead_time"].max())

print("Minimum weekend nights:", df["stays_in_weekend_nights"].min())
print("Maximum weekend nights:", df["stays_in_weekend_nights"].max())

print("Minimum weekday nights:", df["stays_in_week_nights"].min())
print("Maximum weekday nights:", df["stays_in_week_nights"].max())

print("Minimum adults:", df["adults"].min())
print("Maximum adults:", df["adults"].max())

print("Minimum children:", df["children"].min())
print("Maximum children:", df["children"].max())

print("Minimum babies:", df["babies"].min())
print("Maximum babies:", df["babies"].max())

Minimum ADR: -6.38
Maximum ADR: 5400.0
Minimum lead time: 0
Maximum lead time: 737
Minimum weekend nights: 0
Maximum weekend nights: 19
Minimum weekday nights: 0
Maximum weekday nights: 50
Minimum adults: 0
Maximum adults: 55
Minimum children: 0.0
Maximum children: 10.0
Minimum babies: 0
Maximum babies: 10

**Data Cleaning & Data Quality**

In [ ]:
df_raw = df.copy()

In [ ]:
df["children"] = df["children"].fillna(0)
df["country"] = df["country"].fillna("Unknown")
df["agent"] = df["agent"].fillna(0)
df["company"] = df["company"].fillna(0)

In [ ]:
duplicate_rows = df[df.duplicated(keep=False)]

print("Duplicate rows:", len(duplicate_rows))
print("Duplicate groups:", df.duplicated().sum())

Duplicate rows: 40165
Duplicate groups: 31994

In [ ]:
duplicate_analysis = (
    duplicate_rows
    .groupby(["hotel", "is_canceled"])
    .size()
    .reset_index(name="count")
)

duplicate_analysis

          hotel  is_canceled  count
0    City Hotel            0  12281
1    City Hotel            1  19467
2  Resort Hotel            0   4433
3  Resort Hotel            1   3984

In [ ]:
duplicate_rows["reservation_status"].value_counts()

reservation_status
Canceled     23181
Check-Out    16714
No-Show        270
Name: count, dtype: int64

In [ ]:
before = len(df)

df = df.drop_duplicates().reset_index(drop=True)

after = len(df)

print("Rows before:", before)
print("Rows after:", after)
print("Rows removed:", before - after)

Rows before: 119390
Rows after: 87396
Rows removed: 31994

In [ ]:
df["arrival_date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str) + "-" +
    df["arrival_date_month"] + "-" +
    df["arrival_date_day_of_month"].astype(str),
    format="%Y-%B-%d"
)

In [ ]:
df[[
    "arrival_date_year",
    "arrival_date_month",
    "arrival_date_day_of_month",
    "arrival_date"
]].head()

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,arrival_date
0,2015,July,1,2015-07-01
1,2015,July,1,2015-07-01
2,2015,July,1,2015-07-01
3,2015,July,1,2015-07-01
4,2015,July,1,2015-07-01

In [ ]:
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

In [ ]:
df["total_guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

In [ ]:
df["estimated_revenue"] = (
    df["adr"] * df["total_stay_nights"]
)

In [ ]:
print("Negative ADR:", (df["adr"] < 0).sum())
print("Zero ADR:", (df["adr"] == 0).sum())

print("Zero adults:", (df["adults"] == 0).sum())

print("Zero guests:", (df["total_guests"] == 0).sum())

print("Zero-night stays:", (df["total_stay_nights"] == 0).sum())

Negative ADR: 1
Zero ADR: 1778
Zero adults: 385
Zero guests: 166
Zero-night stays: 651

In [ ]:
df[df["adr"] < 0][[
    "hotel",
    "is_canceled",
    "adults",
    "children",
    "babies",
    "total_stay_nights",
    "adr",
    "reservation_status"
]]

,hotel,is_canceled,adults,children,babies,total_stay_nights,adr,reservation_status
11591,Resort Hotel,0,2,0.0,0,10,-6.38,Check-Out

In [ ]:
df[df["adults"] == 0][[
    "hotel",
    "is_canceled",
    "adults",
    "children",
    "babies",
    "total_stay_nights",
    "adr",
    "reservation_status"
]].head(20)

,hotel,is_canceled,adults,children,babies,total_stay_nights,adr,reservation_status
2088,Resort Hotel,0,0,0.0,0,3,0.0,Check-Out
2224,Resort Hotel,0,0,0.0,0,0,0.0,Check-Out
2804,Resort Hotel,0,0,0.0,0,3,0.0,Check-Out
3091,Resort Hotel,0,0,0.0,0,5,0.0,Check-Out
3099,Resort Hotel,0,0,0.0,0,6,0.0,Check-Out
3325,Resort Hotel,1,0,0.0,0,0,0.0,Canceled
7039,Resort Hotel,1,0,0.0,0,0,0.0,Canceled
26491,Resort Hotel,0,0,0.0,0,10,28.0,Check-Out
26726,Resort Hotel,0,0,0.0,0,1,0.0,Check-Out
27391,Resort Hotel,0,0,0.0,0,12,0.0,Check-Out
29113,Resort Hotel,0,0,0.0,0,8,0.0,Check-Out
31457,Resort Hotel,0,0,0.0,0,7,0.0,Check-Out
34135,City Hotel,0,0,0.0,0,7,0.0,Check-Out
34401,City Hotel,0,0,0.0,0,2,0.0,Check-Out
34444,City Hotel,0,0,3.0,0,2,9.0,Check-Out
34475,City Hotel,0,0,0.0,0,29,0.0,Check-Out
34502,City Hotel,0,0,2.0,0,3,6.0,Check-Out
34509,City Hotel,0,0,0.0,0,4,0.0,Check-Out
34670,City Hotel,0,0,2.0,0,2,6.0,Check-Out
35032,City Hotel,0,0,2.0,0,1,0.0,Check-Out

In [ ]:
df["adr_invalid"] = df["adr"] < 0

print("Invalid ADR records:", df["adr_invalid"].sum())

Invalid ADR records: 1

In [ ]:
df.loc[df["adr_invalid"], "adr"] = np.nan

In [ ]:
zero_adults = df[df["adults"] == 0]

zero_adults[[
    "hotel",
    "is_canceled",
    "children",
    "babies",
    "total_guests",
    "total_stay_nights",
    "adr",
    "reservation_status"
]].head(20)

,hotel,is_canceled,children,babies,total_guests,total_stay_nights,adr,reservation_status
2088,Resort Hotel,0,0.0,0,0.0,3,0.0,Check-Out
2224,Resort Hotel,0,0.0,0,0.0,0,0.0,Check-Out
2804,Resort Hotel,0,0.0,0,0.0,3,0.0,Check-Out
3091,Resort Hotel,0,0.0,0,0.0,5,0.0,Check-Out
3099,Resort Hotel,0,0.0,0,0.0,6,0.0,Check-Out
3325,Resort Hotel,1,0.0,0,0.0,0,0.0,Canceled
7039,Resort Hotel,1,0.0,0,0.0,0,0.0,Canceled
26491,Resort Hotel,0,0.0,0,0.0,10,28.0,Check-Out
26726,Resort Hotel,0,0.0,0,0.0,1,0.0,Check-Out
27391,Resort Hotel,0,0.0,0,0.0,12,0.0,Check-Out
29113,Resort Hotel,0,0.0,0,0.0,8,0.0,Check-Out
31457,Resort Hotel,0,0.0,0,0.0,7,0.0,Check-Out
34135,City Hotel,0,0.0,0,0.0,7,0.0,Check-Out
34401,City Hotel,0,0.0,0,0.0,2,0.0,Check-Out
34444,City Hotel,0,3.0,0,3.0,2,9.0,Check-Out
34475,City Hotel,0,0.0,0,0.0,29,0.0,Check-Out
34502,City Hotel,0,2.0,0,2.0,3,6.0,Check-Out
34509,City Hotel,0,0.0,0,0.0,4,0.0,Check-Out
34670,City Hotel,0,2.0,0,2.0,2,6.0,Check-Out
35032,City Hotel,0,2.0,0,2.0,1,0.0,Check-Out

In [ ]:
df["invalid_guest_count"] = df["total_guests"] == 0

print(
    "Records with zero total guests:",
    df["invalid_guest_count"].sum()
)

Records with zero total guests: 166

In [ ]:
Q1 = df["adr"].quantile(0.25)
Q3 = df["adr"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Lower bound: -21.0
Upper bound: 227.0

In [ ]:
df["adr_outlier"] = (
    (df["adr"] < lower_bound) |
    (df["adr"] > upper_bound)
)

print("ADR outliers:", df["adr_outlier"].sum())

ADR outliers: 2490

In [ ]:
for col in ["meal", "market_segment", "distribution_channel"]:
    print(
        col,
        "Undefined:",
        (df[col] == "Undefined").sum()
    )

meal Undefined: 492
market_segment Undefined: 2
distribution_channel Undefined: 5

In [ ]:
quality_report = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Rows",
        "Negative ADR",
        "Zero Adult Records",
        "Zero Guest Records",
        "ADR Outliers"
    ],
    "Count": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        (df["adr"] < 0).sum(),
        (df["adults"] == 0).sum(),
        (df["total_guests"] == 0).sum(),
        df["adr_outlier"].sum()
    ]
})

quality_report

               Metric  Count
0          Total Rows  87396
1       Total Columns     39
2      Missing Values      1
3      Duplicate Rows      0
4        Negative ADR      0
5  Zero Adult Records    385
6  Zero Guest Records    166
7        ADR Outliers   2490

In [ ]:
df.loc[df["adr_invalid"], "adr"] = 0

In [ ]:
print(df.isnull().sum().sum())

0

In [ ]:
df = df[df["total_guests"] > 0].copy()

In [ ]:
print("Rows after removing zero-guest records:", len(df))

Rows after removing zero-guest records: 87230

In [ ]:
df["estimated_revenue"] = (
    df["adr"] * df["total_stay_nights"]
)

In [ ]:
print("Final Shape:", df.shape)

print("\nMissing values:", df.isnull().sum().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Zero guests:", (df["total_guests"] == 0).sum())

print("Negative ADR:", (df["adr"] < 0).sum())

print("ADR outliers:", df["adr_outlier"].sum())

print("\nData types:")
print(df.dtypes)

Final Shape: (87230, 39)

Missing values: 0
Duplicate rows: 0
Zero guests: 0
Negative ADR: 0
ADR outliers: 2490

Data types:
hotel                                     object
is_canceled                                int64
lead_time                                  int64
arrival_date_year                          int64
arrival_date_month                        object
arrival_date_week_number                   int64
arrival_date_day_of_month                  int64
stays_in_weekend_nights                    int64
stays_in_week_nights                       int64
adults                                     int64
children                                 float64
babies                                     int64
meal                                      object
country                                   object
market_segment                            object
distribution_channel                      object
is_repeated_guest                          int64
previous_cancellations                     int64
previous_bookings_not_canceled             int64
reserved_room_type                        object
assigned_room_type                        object
booking_changes                            int64
deposit_type                              object
agent                                    float64
company                                  float64
days_in_waiting_list                       int64
customer_type                             object
adr                                      float64
required_car_parking_spaces                int64
total_of_special_requests                  int64
reservation_status                        object
reservation_status_date                   object
arrival_date                      datetime64[ns]
total_stay_nights                          int64
total_guests                             float64
estimated_revenue                        float64
adr_invalid                                 bool
invalid_guest_count                         bool
adr_outlier                                 bool
dtype: object

In [ ]:
df.to_csv(base_path + "hotel_bookings_cleaned.csv", index=False)