In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
base_path = "/content/drive/MyDrive/AI-Powered Hospitality Revenue Optimization/Dataset/"

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(base_path + "hotel_bookings_cleaned.csv")

In [5]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,total_stay_nights,total_guests,estimated_revenue,adr_invalid,invalid_guest_count,adr_outlier
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,01-07-15,2015-07-01,0,2.0,0.0,False,False,False
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Check-Out,01-07-15,2015-07-01,0,2.0,0.0,False,False,False
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Check-Out,02-07-15,2015-07-01,1,1.0,75.0,False,False,False
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Check-Out,02-07-15,2015-07-01,1,1.0,75.0,False,False,False
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,03-07-15,2015-07-01,2,2.0,196.0,False,False,False

In [6]:
total_bookings = len(df)
print(total_bookings)

87230

In [7]:
cancellations = df["is_canceled"].sum()
print(cancellations)

24009

In [8]:
cancellation_rate = cancellations / total_bookings * 100
print(cancellation_rate)

27.523787687722113

In [9]:
avg_adr = df["adr"].mean()
print(avg_adr)

106.51810386334978

In [10]:
total_revenue = df["estimated_revenue"].sum()
print(total_revenue)

34451654.92999999

In [11]:
avg_stay = df["total_stay_nights"].mean()
print(avg_stay)

3.6285337613206465

In [12]:
hotel_summary = df.groupby("hotel").agg(
    bookings=("hotel", "size"),
    cancellations=("is_canceled", "sum"),
    avg_adr=("adr", "mean"),
    revenue=("estimated_revenue", "sum"),
    avg_stay=("total_stay_nights", "mean")
).reset_index()

hotel_summary["cancellation_rate"] = (
    hotel_summary["cancellations"] /
    hotel_summary["bookings"] * 100
)

hotel_summary.round(2)

,hotel,bookings,cancellations,avg_adr,revenue,avg_stay,cancellation_rate
0,City Hotel,53274,16035,111.27,18765033.36,3.14,30.10
1,Resort Hotel,33956,7974,99.06,15686621.57,4.39,23.48

In [13]:
monthly_demand = (
    df.groupby(["arrival_date_year", "arrival_date_month", "hotel"])
      .size()
      .reset_index(name="bookings")
)

monthly_demand.head()

   arrival_date_year arrival_date_month         hotel  bookings
0               2015             August    City Hotel      1101
1               2015             August  Resort Hotel      1346
2               2015           December    City Hotel      1015
3               2015           December  Resort Hotel       960
4               2015               July    City Hotel       393

In [14]:
segment = df.groupby("market_segment").agg(
    bookings=("hotel", "size"),
    cancellations=("is_canceled", "sum"),
    avg_adr=("adr", "mean"),
    revenue=("estimated_revenue", "sum")
).reset_index()

segment["cancellation_rate"] = (
    segment["cancellations"] /
    segment["bookings"] * 100
)

segment.sort_values("revenue", ascending=False).round(2)

,market_segment,bookings,cancellations,avg_adr,revenue,cancellation_rate
6,Online TA,51553,18242,118.30,22259326.55,35.38
5,Offline TA/TO,13855,2057,81.95,5416464.95,14.85
3,Direct,11780,1737,116.78,4855042.75,14.75
4,Groups,4922,1332,75.17,1238520.72,27.06
2,Corporate,4200,509,68.34,594144.08,12.12
0,Aviation,226,45,100.61,83033.36,19.91
1,Complementary,692,85,3.09,5074.52,12.28
7,Undefined,2,2,15.00,48.00,100.00

In [15]:
channel = df.groupby("distribution_channel").agg(
    bookings=("hotel", "size"),
    cancellations=("is_canceled", "sum"),
    avg_adr=("adr", "mean"),
    revenue=("estimated_revenue", "sum")
).reset_index()

channel["cancellation_rate"] = (
    channel["cancellations"] /
    channel["bookings"] * 100
)

channel.sort_values("revenue", ascending=False).round(2)

,distribution_channel,bookings,cancellations,avg_adr,revenue,cancellation_rate
3,TA/TO,69028,21400,108.72,28573700.15,31.00
1,Direct,12954,1923,109.39,4999030.14,14.84
0,Corporate,5062,646,68.77,834124.82,12.76
2,GDS,181,36,120.32,43628.82,19.89
4,Undefined,5,4,46.24,1171.00,80.00

In [16]:
lead_time = df.groupby("is_canceled")["lead_time"].mean()
print(lead_time)

is_canceled
0     70.185555
1    105.738306
Name: lead_time, dtype: float64

In [17]:
df.groupby("is_canceled")["lead_time"].describe()

               count        mean        std  min   25%   50%    75%    max
is_canceled
0            63221.0   70.185555  81.653591  0.0   7.0  38.0  110.0  737.0
1            24009.0  105.738306  91.846131  0.0  32.0  80.0  158.0  629.0

In [18]:
monthly_revenue = (
    df.groupby(["arrival_date_year", "arrival_date_month"])
      ["estimated_revenue"]
      .sum()
      .reset_index()
)

monthly_revenue.sort_values(
    "estimated_revenue",
    ascending=False
).head(10)

    arrival_date_year arrival_date_month  estimated_revenue
19               2017             August         3131402.33
22               2017               July         2841704.81
7                2016             August         2701783.79
11               2016               July         2093982.77
23               2017               June         2086028.60
25               2017                May         1873898.93
18               2017              April         1662076.31
17               2016          September         1617920.90
12               2016               June         1409564.05
0                2015             August         1405796.27

In [19]:
print("Average ADR:", df["adr"].mean())
print("Total Revenue:", df["estimated_revenue"].sum())
print("Average Revenue per Booking:", df["estimated_revenue"].mean())

Average ADR: 106.51810386334978
Total Revenue: 34451654.92999999
Average Revenue per Booking: 394.9519079445144

In [20]:
hotel_summary = (
    df.groupby('hotel')
      .agg(
          bookings=('hotel', 'size'),
          cancellations=('is_canceled', 'sum'),
          avg_adr=('adr', 'mean'),
          total_revenue=('estimated_revenue', 'sum'),
          avg_stay_nights=('total_stay_nights', 'mean'),
          avg_lead_time=('lead_time', 'mean')
      )
      .reset_index()
)

hotel_summary['cancellation_rate'] = (
    hotel_summary['cancellations'] / hotel_summary['bookings'] * 100
)

hotel_summary['avg_revenue_per_booking'] = (
    hotel_summary['total_revenue'] / hotel_summary['bookings']
)

hotel_summary = hotel_summary.round({
    'avg_adr': 2,
    'total_revenue': 2,
    'avg_stay_nights': 2,
    'avg_lead_time': 2,
    'cancellation_rate': 2,
    'avg_revenue_per_booking': 2
})

hotel_summary.to_csv(base_path + 'hotel_summary.csv', index=False)

hotel_summary

,hotel,bookings,cancellations,avg_adr,total_revenue,avg_stay_nights,avg_lead_time,cancellation_rate,avg_revenue_per_booking
0,City Hotel,53274,16035,111.27,18765033.36,3.14,77.79,30.10,352.24
1,Resort Hotel,33956,7974,99.06,15686621.57,4.39,83.39,23.48,461.97

In [28]:
from sklearn.ensemble import IsolationForest

anomaly_features = [
    'adr',
    'total_stay_nights',
    'lead_time',
    'total_guests',
    'total_of_special_requests'
]

X = df[anomaly_features].copy()

iso_forest = IsolationForest(
    contamination=0.02,
    random_state=42
)

df['anomaly_flag'] = iso_forest.fit_predict(X)

df['anomaly_flag'] = df['anomaly_flag'].map({
    -1: 1,
     1: 0
})

anomaly_summary = (
    df.groupby(['hotel', 'anomaly_flag'])
      .agg(
          booking_count=('hotel', 'size'),
          avg_adr=('adr', 'mean'),
          avg_stay_nights=('total_stay_nights', 'mean'),
          avg_lead_time=('lead_time', 'mean'),
          avg_guests=('total_guests', 'mean'),
          avg_special_requests=('total_of_special_requests', 'mean'),
          estimated_revenue=('estimated_revenue', 'sum')
      )
      .reset_index()
)

hotel_totals = (
    df.groupby('hotel')
      .size()
      .reset_index(name='hotel_total_bookings')
)

anomaly_summary = anomaly_summary.merge(
    hotel_totals,
    on='hotel',
    how='left'
)

anomaly_summary['percentage_of_hotel_bookings'] = (
    anomaly_summary['booking_count']
    / anomaly_summary['hotel_total_bookings']
    * 100
)

anomaly_summary['status'] = anomaly_summary['anomaly_flag'].map({
    1: 'Anomaly',
    0: 'Normal'
})

anomaly_summary = anomaly_summary[
    [
        'hotel',
        'status',
        'booking_count',
        'percentage_of_hotel_bookings',
        'avg_adr',
        'avg_stay_nights',
        'avg_lead_time',
        'avg_guests',
        'avg_special_requests',
        'estimated_revenue'
    ]
]

anomaly_summary = anomaly_summary.round(2)

anomaly_summary.to_csv(base_path + 'anomaly_summary.csv', index=False)

print("Anomaly summary created successfully.")
print(f"Total anomalies: {(df['anomaly_flag'] == 1).sum()}")
print(f"Total normal bookings: {(df['anomaly_flag'] == 0).sum()}")

anomaly_summary

Anomaly summary created successfully.
Total anomalies: 1745
Total normal bookings: 85485

,hotel,status,booking_count,percentage_of_hotel_bookings,avg_adr,avg_stay_nights,avg_lead_time,avg_guests,avg_special_requests,estimated_revenue
0,City Hotel,Normal,52647,98.82,110.70,3.11,77.05,2.01,0.70,18205656.93
1,City Hotel,Anomaly,627,1.18,159.56,6.03,140.36,3.11,1.62,559376.43
2,Resort Hotel,Normal,32838,96.71,96.40,4.22,80.24,2.00,0.65,14156139.84
3,Resort Hotel,Anomaly,1118,3.29,177.04,9.52,175.91,3.27,1.47,1530481.73